apiVersion: v1
kind: Service
metadata:
  name: ecsdemo-frontend
  namespace: clb-test
spec:
  selector:
    app: ecsdemo-frontend
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 3000

